misc: Small fixes
- Properly output everything to standard error on trap error
- Use `__bake_is_tty` function

diff --git a/bake b/bake
--- a/bake
+++ b/bake
@@ -5,15 +5,14 @@ if [ "$0" != "${BASH_SOURCE[0]}" ]; then
 	return 1
 fi
 
-
 # Private API (unstable)
 __bake_trap_err() {
 	local err_code=$?
 
 	if __bake_is_tty; then
-		printf "\033[0;33m%s\033[0m %s\n" "Warn (bake)" "Your 'Bakefile.sh' did not exit successfully" >&2
+		printf "\033[0;31m%s\033[0m %s\n" "Error (bake)" "Your 'Bakefile.sh' did not exit successfully"
 	else
-		printf '%s: %s\n' 'Warn (bake)' "Your 'Bakefile.sh' did not exit successfully" >&2
+		printf '%s: %s\n' 'Error (bake)' "Your 'Bakefile.sh' did not exit successfully"
 	fi
 
 	if (( ${#FUNCNAME[@]} >> 2 )); then
@@ -24,7 +23,7 @@ __bake_trap_err() {
 	fi
 
 	exit $err_code
-}
+} >&2
 
 __bake_is_tty() {
 	! [[ -v NO_COLOR || $TERM == dumb ]]
@@ -40,7 +39,6 @@ __bake_die() {
 	exit 1
 }
 
-
 # Public API
 die() {
 	if [ -n "$1" ]; then
@@ -53,26 +51,26 @@ die() {
 }
 
 error() {
-	if [[ -v NO_COLOR || $TERM = dumb ]]; then
-		printf '%s: %s\n' 'Error' "$1" >&2
-	else
+	if __bake_is_tty; then
 		printf "\033[0;31m%s\033[0m: %s\n" 'Error' "$1" >&2
+	else
+		printf '%s: %s\n' 'Error' "$1" >&2
 	fi
 }
 
 warn() {
-	if [[ -v NO_COLOR || $TERM = dumb ]]; then
-		printf '%s: %s\n' 'Warn' "$1" >&2
-	else
+	if __bake_is_tty; then
 		printf "\033[1;33m%s\033[0m: %s\n" 'Warn' "$1" >&2
+	else
+		printf '%s: %s\n' 'Warn' "$1" >&2
 	fi
 }
 
 info() {
-	if [[ -v NO_COLOR || $TERM = dumb ]]; then
-		printf '%s: %s\n' 'Info' "$1"
-	else
+	if __bake_is_tty; then
 		printf "\033[0;34m%s\033[0m: %s\n" 'Info' "$1"
+	else
+		printf '%s: %s\n' 'Info' "$1"
 	fi
 }
 
