feat: Implement `bake.has_flag`. Closes #11

diff --git a/bake b/bake
--- a/bake
+++ b/bake
@@ -91,6 +91,26 @@ bake.assert_cmd() {
 	fi
 }
 
+bake.has_flag() {
+	local flag_name="$1"
+
+	if [ -z "$flag_name" ]; then
+		bake.die "Argument must not be empty"
+	fi
+	if ! shift; then
+		bake.die 'Failed to shift'
+	fi
+
+	local arg=
+	for arg; do
+		if [ "$arg" = "$flag_name" ]; then
+			return 0
+		fi
+	done; unset -v arg
+
+	return 1
+}
+
 # @description Change the behavior of Bake. See [guide.md](./docs/guide.md) for details
 # @arg $1 string Name of config property to change
 # @arg $2 string New value of config property
@@ -341,6 +361,7 @@ __bake_parse_args() {
 	-v)
 		local bake_version='1.9.0'
 		printf '%s\n' "Version: $bake_version"
+		exit 0
 		;;
 	-h)
 		local flag_help='yes'
